### ISSUE TITLE
cant load .epro files in android 7.1 (CM14.1)

### ISSUE THREAD

**Issue by pedrazadixon** [easypro/eProxy#1]
This is logcat when try import files in android 7.1 (CM14.1), the storage is properly granted permission in the app settings.

Logcat: 
[Log_2016-11-28_15-39-25.txt](https://github.com/easypro/eProxy/files/617425/Log_2016-11-28_15-39-25.txt)

thanks in advance

**Comment by easypro** [comment]
@pedrazadixon, is eProxy force close after import file?
Do you have try create dummy config file, save it and load again?

**Comment by pedrazadixon** [comment]
@easypro please see this video: [https://youtu.be/uSLzeu5lkVY](url)
The app not crash or close. only the message "cant load configuration" is displayed.
This is catlog recorded during the video [http://pastebin.com/raw/2dcd5JPh](url)

**Comment by easypro** [comment]
@pedrazadixon please send cfg file which it can't be load, I need analyze it.

**Comment by pedrazadixon** [comment]
@easypro this is the file use in video: 
[https://drive.google.com/file/d/0B5lyToxn8S29NGVEN2Vud3dZcUU/view?usp=sharing](https://drive.google.com/file/d/0B5lyToxn8S29NGVEN2Vud3dZcUU/view?usp=sharing)

**Comment by easypro** [comment]
@pedrazadixon you can test this version [https://github.com/easypro/eProxy/releases/tag/417](url)

**Comment by pedrazadixon** [comment]
@easypro can't load url 
thanks in advance

**Comment by easypro** [comment]
@pedrazadixon [link updated](https://github.com/easypro/eProxy/releases)

**Comment by pedrazadixon** [comment]
Solved!
@easypro :smiley: :smiley:  v2.7.27-NIGHTLY(417) works perfect in android 7.x!
Now I can import correctly .ePro files in Android Naugat systems.
Thank very much for your excelent support.
Regards and go ahead friend.
