### ISSUE TITLE
Sharing Internet 

### ISSUE THREAD

**Issue by Maggot8701** [easypro/eProxy#2]
I connect using ssh and I have Internet in my smartphone,  but i try Sharing and no it works

what are the correct steps for sharing a direct ssh conection via wifi?
is it possible?

**Comment by Maggot8701** [comment]
sharing via vpn to wifo option

**Comment by easypro** [comment]
@Maggot8701 You must run with mode tun2socks. so you can sharing ssh connection..

**Comment by Maggot8701** [comment]
I have tried to share vpn to wifi in different ways but still not accomplish this, the client can be conected but can't surf internet.

You can share me the correct steps to accomplish this?

I have CM13 system and I have this rooted correctly.

**Comment by easypro** [comment]
@Maggot8701 try use manual command like [this](http://digiex.net/guides-reviews/guides-tutorials/mobile-devices/13974-android-phone-vpn-gateway-bypass-tethering-block.html)

**Comment by pedrazadixon** [comment]
I try follow the guide on android 6 but netcfg command not found. 
Some android 5.x 6.x and 7.x can't contain this command. 
Other way for share vpn to WiFi?

**Comment by pedrazadixon** [comment]
@Maggot8701 
STEP 1: You need a rooted device
STEP 2: Download a terminal emulator. like [termux](https://play.google.com/store/apps/details?id=com.termux)
STEP 3: Activate your wifi hotspot and connect to your VPN
STEP 4: launch Terminal emulator and on the first line type "su" (without the quotes) and press enter
STEP 4: Copy and paste this to the Terminal Emulator.
`iptables -t filter -F FORWARD
iptables -t nat -F POSTROUTING
iptables -t filter -I FORWARD -j ACCEPT
iptables -t nat -I POSTROUTING -j MASQUERADE
ip rule add from 192.168.43.0/24 lookup 61
ip route add default dev tun0 scope link table 61
ip route add 192.168.43.0/24 dev wlan0 scope link table 61
ip route add broadcast 255.255.255.255 dev wlan0 scope link table 61`
STEP 7: Enjoy your shared vpn.
I tested this in android 6 without netcfg command and works fine.
