### ISSUE TITLE
v2.7.27-NIGHTLY(417) auto reconnet not work.

### ISSUE THREAD

**Issue by pedrazadixon** [easypro/eProxy#3]
In v2.7.27-NIGHTLY(417) auto reconnect not work (when direct ssh is ticked).
In previus v2.7.26-SNAPSHOT(416) it worked fine.
I backing to previous version for now.

**Comment by easypro** [comment]
@pedrazadixon you can test [new version](https://github.com/easypro/eProxy/releases/tag/418)

**Comment by pedrazadixon** [comment]
Solved, thanks again.
